In [2]:

# Python program to inverse 
# a matrix using numpy 
  
# Import required package 
import numpy as np 
  
# Taking a 3 * 3 matrix 
A = np.array([[9, 6, 1], 
              [8, 4, 5], 
              [5, 3, 2]]) 
  
# Calculating the inverse of the matrix 
print(np.linalg.inv(A))


[[ 1.4  1.8 -5.2]
 [-1.8 -2.6  7.4]
 [-0.8 -0.6  2.4]]
