In [4]:
# importing numpy for matrix operations 
import numpy 
  
# initializing matrices 
x = numpy.array([[5, 2], [6, 4]]) 
y = numpy.array([[7, 6], [9, 8]]) 
  
print ("The element wise addition of matrix is : ") 
print (numpy.add(x,y)) 
 
print ("The element wise subtraction of matrix is : ") 
print (numpy.subtract(x,y)) 
   
print ("The element wise division of matrix is : ") 
print (numpy.divide(x,y)) 
 
print ("The element wise multiplication of matrix is :")
print (numpy.multiply(x,y))

print ("Matrix transposion")
print (x.T)

The element wise addition of matrix is : 
[[12  8]
 [15 12]]
The element wise subtraction of matrix is : 
[[-2 -4]
 [-3 -4]]
The element wise division of matrix is : 
[[0.71428571 0.33333333]
 [0.66666667 0.5       ]]
The element wise multiplication of matrix is :
[[35 12]
 [54 32]]
Matrix transposion
[[5 6]
 [2 4]]
